import { useState } from "react";
import ProgressTracker from "@/components/ProgressTracker";

export default function DocAgent() {
  const [tab, setTab] = useState('readme');
  const readme = `# Project\nThis is a sample README generated by Doc Agent.`;
  const api = `# API\nGET /api/ideas`;
  const pitch = `# Pitch\nOne-liner: A powerful AI teammate for hackathons.`;

  const download = (type: string) => {
    alert(`Mock download: ${type}`);
  };

  return (
    <div className="container py-12">
      <div className="grid gap-8 md:grid-cols-4">
        <main className="md:col-span-3 space-y-6">
          <div className="rounded-xl border border-white/10 bg-background/60 p-4">
            <div className="flex items-center justify-between">
              <h2 className="text-2xl font-bold">Doc Agent</h2>
              <div className="flex items-center gap-2">
                <button onClick={() => setTab('readme')} className={`px-3 py-1 rounded ${tab==='readme' ? 'bg-background text-foreground font-semibold' : 'text-muted-foreground'}`}>README.md</button>
                <button onClick={() => setTab('api')} className={`px-3 py-1 rounded ${tab==='api' ? 'bg-background text-foreground font-semibold' : 'text-muted-foreground'}`}>API Docs</button>
                <button onClick={() => setTab('pitch')} className={`px-3 py-1 rounded ${tab==='pitch' ? 'bg-background text-foreground font-semibold' : 'text-muted-foreground'}`}>Pitch Deck</button>
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-white/10 bg-background/60 p-6">
            <pre className="whitespace-pre-wrap text-sm text-muted-foreground">{tab==='readme'?readme:tab==='api'?api:pitch}</pre>
          </div>

          <div className="flex gap-3">
            <button onClick={() => download('pdf')} className="rounded-md bg-gradient-to-r from-[hsl(var(--primary))] to-[hsl(var(--accent))] px-4 py-2 text-white">Export as PDF</button>
            <button onClick={() => download('ppt')} className="rounded-md border border-white/10 px-4 py-2">Export as PPT</button>
          </div>
        </main>

        <aside className="hidden md:block md:col-span-1 space-y-4">
          <div className="rounded-lg border border-white/10 bg-background/60 p-4">
            <h4 className="font-semibold">Elevator Pitch</h4>
            <p className="mt-2 text-sm text-muted-foreground">A concise line to pitch your project to judges and stakeholders.</p>
          </div>

          <ProgressTracker step={4} />
        </aside>
      </div>
    </div>
  );
}
