import IdeaCard from "@/components/IdeaCard";
import ProgressTracker from "@/components/ProgressTracker";

const ideas = [
  { id: '1', title: 'AutoCrop AI', description: 'Smart crop recommendations using satellite imagery to maximize yield.', feasibility: 'High' },
  { id: '2', title: 'Climate Chatbot', description: 'Assist communities with climate adaptation steps and resources.', feasibility: 'Medium' },
  { id: '3', title: 'Carbon Auditor', description: 'Estimate carbon footprints from project inputs and suggest reductions.', feasibility: 'High' },
  { id: '4', title: 'GreenFin Insights', description: 'AI to score sustainability of investments for fintech apps.', feasibility: 'Low' },
  { id: '5', title: 'Smart Mentor', description: 'Match mentors to teams based on skills and needs.', feasibility: 'Medium' },
];

export default function IdeaAgent() {
  return (
    <div className="container py-12">
      <div className="grid gap-8 md:grid-cols-4">
        <div className="md:col-span-3">
          <h2 className="text-2xl font-bold">AI-generated project ideas</h2>
          <p className="mt-2 text-sm text-muted-foreground">Browse curated ideas generated by Idea Agent. Pick one to continue the workflow.</p>

          <div className="mt-6 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {ideas.map((it) => (
              <IdeaCard key={it.id} title={it.title} description={it.description} feasibility={it.feasibility} />
            ))}
          </div>
        </div>

        <aside className="hidden md:block md:col-span-1">
          <ProgressTracker step={1} />
        </aside>
      </div>
    </div>
  );
}
